Repository palm-springs/PalmSpringClient, pull requests merged in 2024-06, with the labels that each got.

#476 Feat/#475/draft save fix
  app/[team]/editor/article/[articleId]/publish/page.tsx
  components/dashboard/category/CategoryTemplate.tsx
  components/editor/TextEditorImport.tsx
Labels: fix

#477 RELEASE - v3.9.1
  app/[team]/editor/article/[articleId]/publish/page.tsx
  components/dashboard/category/CategoryTemplate.tsx
  components/editor/TextEditorImport.tsx
Labels: fix

#497 Feat/#496/landing footer business info
  app/(auth)/layout.tsx
  app/team/page.tsx
  components/landing/Footer.tsx
  components/landing/Header.tsx
  components/landing/LandingPage.tsx
  public/icons/index.ts
  public/icons/palmsblog_logo_vector.svg
Labels: feat

#499 RELEASE - v3.10.0
  api/blog.ts
  app/(auth)/layout.tsx
  app/team/page.tsx
  components/dashboard/blogBasicInfo/BlogConfigTemplate.tsx
  components/dashboard/blogBasicInfo/BlogDescribeText.tsx
  components/dashboard/blogBasicInfo/BlogFooterDescription.tsx
  components/dashboard/blogBasicInfo/BlogMainImge.tsx
  components/dashboard/blogBasicInfo/BlogMetaDataImage.tsx
  components/dashboard/blogBasicInfo/BlogMetaDataPreview.tsx
  components/dashboard/blogBasicInfo/BlogSubHeading.tsx
  components/dashboard/blogBasicInfo/BlogTemplateDesign.tsx
  components/landing/Footer.tsx
  components/landing/Header.tsx
  components/landing/LandingPage.tsx
  hooks/blog.ts
  public/icons/index.ts
  public/icons/palmsblog_logo_vector.svg
Labels: feat

#501 hotfix/#500: 구글로그인 먹통 대응 공지문구 추가
  components/auth/login/LoginLanding.tsx
  styles/style.d.ts
  styles/theme.ts
Labels: hotfix

#502 RELEASE - v3.10.1
  components/auth/login/LoginLanding.tsx
  styles/style.d.ts
  styles/theme.ts
Labels: hotfix
