Repository palm-springs/PalmSpringClient, pull requests merged in 2024-07, with the labels that each got.

#506 fix/#505: 대시보드 내 템플릿 설정 뷰 개발환경에서만 보이게끔 수정
  components/dashboard/blogBasicInfo/BlogConfigTemplate.tsx
Labels: fix

#511 Fix: 인증 메일 실패시 404 띄우기
  api/user.ts
  app/(auth)/login/password/reset/page.tsx
  components/auth/AuthRequired.tsx
  components/auth/login/password/reset/PasswordResetLanding.tsx
  components/auth/login/password/reset/PasswordResetUiLanding.tsx
  components/auth/login/password/reset/PasswordVerify.tsx
  components/invite/InviteLanding.tsx
  hooks/auth.ts
Labels: fix

#490 Feat/#479/data tracking UI
  .husky/pre-commit
  .husky/pre-push
  api/dashboard.ts
  app/[team]/dashboard/statistics/[articleId]/page.tsx
  app/[team]/dashboard/statistics/page.tsx
  app/no-team/dashboard/statistics/page.tsx
  app/page.tsx
  app/robots.ts
  app/sitemap.xml
  components/auth/sign-up/email-verify/EmailVerifyLanding.tsx
  components/create-blog/success/LoginSuccessLanding.tsx
  components/dashboard/BasicUserInfo/ui/DeleteButton.tsx
  components/dashboard/DashBoardTemplate.tsx
  components/dashboard/components/BlogList.tsx
  components/dashboard/components/DashBoardNav.tsx
  components/invite/ui/InviteAcceptForm.tsx
  components/no-team/TeamValidation.tsx
  components/statistics/ArticleField.tsx
  components/statistics/ArticleItem.tsx
  components/statistics/ArticleList.tsx
  components/statistics/ArticleListStatistic.tsx
  components/statistics/BlogStatistic.tsx
  components/statistics/BlogStatistics/VisitantCard.tsx
  components/statistics/BlogStatistics/VisitantUI.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/StatisticsTemplate.tsx
  components/statistics/common/Calendar.tsx
  components/statistics/common/Chart.tsx
  components/statistics/detail/ArticleInfo.tsx
  components/statistics/detail/ArticleStatistic.tsx
  components/statistics/detail/StatisticsDetailTemplate.tsx
  constants/mapPageType2Component.tsx
  constants/mapPageType2HeaderInfo.ts
  constants/reservedUrl.ts
  hooks/blog.ts
  hooks/dashboard.ts
  hooks/useGetLastPathName.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  public/icons/arrow-left.svg
  public/icons/ic_calendarArrow.svg
  public/icons/icnChartLogo.svg
  public/icons/icnDecreaseArrow.svg
  public/icons/icnIncreaseArrow.svg
  public/icons/icn_calendar.svg
  public/icons/index.ts
  recoil/atom/dashboard.ts
  recoil/selector/dashboard.ts
  styles/style.d.ts
  styles/theme.ts
  types/dashboard.ts
  utils/getCurrentDateTime.ts
  utils/successLogin.ts
Labels: feat

#517 Feat/#513/new landing 새로운 랜딩페이지 완성
  app/layout.tsx
  app/team/page.tsx
  components/landing/LandingPage.tsx
  components/landing/components/Chart.tsx
  components/landing/components/ColorfulContentBlock.tsx
  components/landing/props/framerMotionProps.tsx
  package.json
  pnpm-lock.yaml
  public/icons/index.ts
  public/icons/palms-logo.svg
  public/images/index.ts
  public/images/landing/customization-image.png
  public/images/landing/default-open-graph.png
  public/images/landing/first-impression-image.png
  public/images/landing/lighthouse-score.png
  public/images/landing/seo-example-image.png
Labels: feat

#518 RELEASE v3.11.5
  app/layout.tsx
  app/team/page.tsx
  components/landing/LandingPage.tsx
  components/landing/components/Chart.tsx
  components/landing/components/ColorfulContentBlock.tsx
  components/landing/props/framerMotionProps.tsx
  package.json
  pnpm-lock.yaml
  public/icons/index.ts
  public/icons/palms-logo.svg
  public/images/index.ts
  public/images/landing/customization-image.png
  public/images/landing/default-open-graph.png
  public/images/landing/first-impression-image.png
  public/images/landing/lighthouse-score.png
  public/images/landing/seo-example-image.png
Labels: feat

#520 Feat/#516/data qa
  components/dashboard/blogBasicInfo/BlogConfigTemplate.tsx
  components/dashboard/components/ui/DashBoardContentContainer.tsx
  components/statistics/BlogStatistics/VisitantCard.tsx
  components/statistics/BlogStatistics/VisitantUI.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Calendar.tsx
  components/statistics/common/Chart.tsx
  components/statistics/detail/StatisticsDetailTemplate.tsx
  package.json
  pnpm-lock.yaml
  public/icons/icn_leftArrow.svg
  public/icons/icn_rightArrow.svg
  public/icons/index.ts
Labels: QA

#523 Feat/#522/calendar qa
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Chart.tsx
Labels: feat, QA

#532 fix/#531: 페이지 임시저장, 발행하기 코드 수정
  app/[team]/editor/page/[pageId]/publish/page.tsx
  components/editor/TextEditorImport.tsx
Labels: fix

#533 RELEASE v3.11.15
  app/[team]/editor/page/[pageId]/publish/page.tsx
  components/editor/TextEditorImport.tsx
Labels: QA

#535 feat/#534:네비게이션, 페이지 상세설명 문구 추가
  components/dashboard/components/DashBoardHeader.tsx
  components/dashboard/components/ui/HeaderContainer.tsx
  components/statistics/BlogStatistics/VisitantCard.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Calendar.tsx
  constants/mapPageType2HeaderInfo.ts
Labels: QA

#536 RELEASE v3.11.16
  components/dashboard/components/DashBoardHeader.tsx
  components/dashboard/components/ui/HeaderContainer.tsx
  components/statistics/BlogStatistics/VisitantCard.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Calendar.tsx
  constants/mapPageType2HeaderInfo.ts
Labels: QA

#537 RELEASE v3.11.17 : 그래프 수정
  components/statistics/BlogStatistics/VistantChart.tsx
Labels: fix

#542 Feat/#540/statistics qa
  components/auth/ui/Title.tsx
  components/create-blog/info/ui/basicInfo/CreateBasicInfoLanding.tsx
  components/create-blog/info/ui/optionInfo/CreateOptionInfoLanding.tsx
  components/dashboard/BasicUserInfo/ui/UserProfile.tsx
  components/editor/TextEditorImport.tsx
  components/editor/publish/ui/ThumbnailInput.tsx
  components/editor/ui/ToolBox.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Calendar.tsx
  components/statistics/common/Chart.tsx
  styles/MobileTextEditorStyle.ts
  styles/TextEditorStyle.ts
  types/dashboard.ts
Labels: fix, QA

#543 RELEASE - v3.11.21
  components/auth/ui/Title.tsx
  components/create-blog/info/ui/basicInfo/CreateBasicInfoLanding.tsx
  components/create-blog/info/ui/optionInfo/CreateOptionInfoLanding.tsx
  components/dashboard/BasicUserInfo/ui/UserProfile.tsx
  components/editor/TextEditorImport.tsx
  components/editor/publish/ui/ThumbnailInput.tsx
  components/editor/ui/ToolBox.tsx
  components/statistics/BlogStatistics/VistantChart.tsx
  components/statistics/common/Calendar.tsx
  components/statistics/common/Chart.tsx
  styles/MobileTextEditorStyle.ts
  styles/TextEditorStyle.ts
  types/dashboard.ts
Labels: fix, QA

#544 Fix: QA 반영
  api/blog.ts
  api/common.ts
  api/dashboard.ts
  components/auth/AuthRequired.tsx
  components/dashboard/BasicUserInfo/ui/UserInfoSaveButton.tsx
  components/dashboard/blogBasicInfo/BlogConfigTemplate.tsx
  components/dashboard/category/CategoryTemplate.tsx
  components/landing/LandingPage.tsx
  hooks/dashboard.ts
  types/blogInfo.ts
  utils/auth.ts
  utils/dashboard.ts
Labels: fix
